#!/usr/bin/env node

/**
 * Generate STATUS.md from the repository's own evidence: git describe, the
 * package version, the generic-channel receipts inside the built bundles when
 * present, the newest release-gate receipt, and the standards review date in
 * the color-foundations manifest. Run with `npm run status`.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

export const STATUS_PATH = 'STATUS.md';
export const GATES_DIRECTORY = 'docs/evidence/gates';
export const MANIFEST_PATH = 'docs/color-foundations-manifest.json';
export const CHANNEL_FILES = Object.freeze([
  { label: 'Production build', path: 'dist/GENERIC_COLOR_BUILDER_CHANNEL.json' },
  { label: 'Candidate build', path: 'figma-candidate/dist/GENERIC_COLOR_BUILDER_CHANNEL.json' },
]);

function gitOutput(args, cwd) {
  const result = spawnSync('git', args, { cwd, encoding: 'utf8' });
  if (result.error || result.status !== 0) return null;
  return result.stdout.trim();
}

function readJsonIfPresent(absolutePath) {
  if (!fs.existsSync(absolutePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(absolutePath, 'utf8'));
  } catch {
    return null;
  }
}

export function findNewestReceipt(rootDir) {
  const gatesDirectory = path.join(rootDir, GATES_DIRECTORY);
  if (!fs.existsSync(gatesDirectory)) return null;
  const directories = fs
    .readdirSync(gatesDirectory, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()
    .reverse();
  for (const directory of directories) {
    const receipt = readJsonIfPresent(path.join(gatesDirectory, directory, 'receipt.json'));
    if (receipt) return { directory: `${GATES_DIRECTORY}/${directory}`, receipt };
  }
  return null;
}

const DAY_MS = 86_400_000;

function utcDate(value) {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null;
  const time = Date.parse(`${value}T00:00:00.000Z`);
  return Number.isNaN(time) ? null : time;
}

/** Whole days from `asOf` to `reviewBy`; negative once the review is overdue. */
export function daysUntil(reviewBy, asOf) {
  const due = utcDate(reviewBy);
  const today = utcDate(asOf);
  if (due === null || today === null) return null;
  return Math.round((due - today) / DAY_MS);
}

export function collectStatus({
  rootDir = ROOT,
  asOf = new Date().toISOString().slice(0, 10),
} = {}) {
  const packageMetadata = readJsonIfPresent(path.join(rootDir, 'package.json')) ?? {};
  const manifest = readJsonIfPresent(path.join(rootDir, MANIFEST_PATH));
  return {
    describe: gitOutput(['describe', '--always'], rootDir),
    branch: gitOutput(['rev-parse', '--abbrev-ref', 'HEAD'], rootDir),
    version: packageMetadata.version ?? null,
    channels: CHANNEL_FILES.map(channel => {
      const parsed = readJsonIfPresent(path.join(rootDir, channel.path));
      return {
        ...channel,
        present: parsed !== null,
        channel: parsed?.channel ?? null,
        qualified: parsed?.qualified ?? null,
      };
    }),
    receipt: findNewestReceipt(rootDir),
    standards: manifest
      ? {
          reviewedAt: manifest.reviewedAt ?? null,
          reviewBy: manifest.reviewBy ?? null,
          reviewOwner: manifest.reviewOwner ?? null,
          asOf,
          daysRemaining: daysUntil(manifest.reviewBy, asOf),
        }
      : null,
  };
}

function describeRemaining(days) {
  if (days === null) return '[TK] days remaining';
  if (days < 0) return `overdue by ${Math.abs(days)} ${Math.abs(days) === 1 ? 'day' : 'days'}`;
  return `${days} ${days === 1 ? 'day' : 'days'} remaining`;
}

function code(value) {
  return `\`${value ?? '[TK]'}\``;
}

export function renderStatus(status) {
  const lines = [
    '# Teul status',
    '',
    'Generated by `npm run status` from the repository’s own evidence. Do not edit by hand.',
    '',
    '## Code',
    '',
    `- Version: ${code(status.version)} (\`package.json\`)`,
    `- Commit: ${code(status.describe)} (\`git describe --always\`), branch ${code(status.branch)}`,
    '- Shipping line: `main` on the owner’s private repository. `github.com/pauljunbear/Teul` is the Community-facing mirror, fast-forwarded when the owner publishes a release.',
    '',
    '## Generic color builder channel',
    '',
  ];
  for (const channel of status.channels) {
    lines.push(
      channel.present
        ? `- ${channel.label} (\`${channel.path}\`): channel ${code(channel.channel)}, qualified ${code(String(channel.qualified))}`
        : `- ${channel.label} (\`${channel.path}\`): not built on this machine`
    );
  }
  lines.push('', '## Release gate', '');
  if (status.receipt) {
    const { directory, receipt } = status.receipt;
    const environment = receipt.environment ?? {};
    const passed = (receipt.steps ?? []).filter(step => step.status === 'passed').length;
    lines.push(
      `- Newest receipt: \`${directory}/receipt.md\``,
      `- Result: ${code(receipt.status)} (${passed} of ${(receipt.steps ?? []).length} steps passed), finished ${receipt.finishedAt ?? '[TK]'}`,
      `- Runtime: Node ${environment.node ?? '[TK]'}, npm ${environment.npm ?? '[TK]'}, commit ${code(environment.shortCommit)}${environment.dirty ? ' (worktree had uncommitted changes)' : ''}`,
      '- The gate is `npm run release-gate`, run locally on Node 22 and Node 24; every run’s receipt is committed under `docs/evidence/gates/`.'
    );
  } else {
    lines.push(
      `- No receipts under \`${GATES_DIRECTORY}/\` yet. Run \`npm run release-gate\` on Node 22 and Node 24 and commit the receipts.`
    );
  }
  lines.push('', '## Standards evidence', '');
  lines.push(
    status.standards
      ? `- Color-foundations ledger (\`${MANIFEST_PATH}\`): reviewed ${status.standards.reviewedAt ?? '[TK]'}, review by ${status.standards.reviewBy ?? '[TK]'}; \`npm run verify:color-foundations\` fails closed after that date.`
      : `- Color-foundations ledger (\`${MANIFEST_PATH}\`): missing.`
  );
  if (status.standards) {
    lines.push(
      `- Standards re-review: due ${status.standards.reviewBy ?? '[TK]'}, owner ${status.standards.reviewOwner ?? '[TK]'}, ${describeRemaining(status.standards.daysRemaining)} (as of ${status.standards.asOf ?? '[TK]'}).`
    );
  }
  lines.push('');
  return lines.join('\n');
}

export function writeStatus({ rootDir = ROOT } = {}) {
  const markdown = renderStatus(collectStatus({ rootDir }));
  fs.writeFileSync(path.join(rootDir, STATUS_PATH), markdown);
  return markdown;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeStatus();
  console.log(`Wrote ${STATUS_PATH}.`);
}
